name: "Deploy Prod"
on:
  push:
    branches: [ main ]

jobs:
  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy
        run: echo DEPLOYING TO PRODUCTION!!
      - name: Deploy in EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY $USER_NAME@$HOST_NAME
            cd $APP_DIR &&
            git pull &&
            npm install
            npm start
