name: "Deploy Prod"
on:
  push:
    branches: [ main ]

jobs:
  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy
        run: echo DEPLOYING TO PRODUCTION!!
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
          HOST_NAME : ${{ secrets.HOST_NAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          echo Step 1
          echo ${PRIVATE_KEY} > private_key.pem && chmod 600 private_key.pem
          echo Step 2
          ssh -o StrictHostKeyChecking=no -i "private_key.pem" ${USER_NAME}@${HOST_NAME}
          cd ${APP_DIR} &&
          git pull &&
          npm install
          npm start
